title: Hadrien Nguyen
description: > # this means to ignore newlines until "baseurl:"
  Professional website for Hadrien Nguyen. Master of Computer Science at the University of Texas at Arlington
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Hadrien Nguyen # add your name
author-img: profile.jpg # add your photo
about-author: > # add description
  I am a game developer and a graduate student. I wanna make cool
  games and pretty images. I am interested in Non-Photorealistic Rendering,
  Stylized Animation, Video Game Design Tools.
social-twitter: Hadrien____ # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: 13hnguyen # add your Github handle
social-linkedin: hadrien-nguyen # add your Linkedin handle
social-email: nguyen.hady@live.fr # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
